development:
  api_key: 1234abc
  owner_url: http://code.macournoyer.com/svn/plugins/defensio

test:
  api_key: 1234abc
  owner_url: http://code.macournoyer.com/svn/plugins/defensio

production:
  api_key: 7fc13352a2d5011ff11c1298ece7dbd4
  owner_url: http://40withegg.com