#!/usr/bin/env ruby
runner = File.dirname(__FILE__) + "/runner"

begin
    if system("RAILS_ENV=production #{runner} 'Feed.refresh_all!'")
        puts "#{Time.now} - OK!"
    else
        puts "#{Time.now} - ERROR!"
    end
rescue => e
    puts "error!"
    puts e
end