#!/usr/bin/env ruby
runner = File.dirname(__FILE__) + "/runner"

begin
    if system("RAILS_ENV=production #{runner} 'Feed.refresh_all!'")
        %w(index post feed article external_article gist link picture quote snippet tweet).each do |file|
          system "rm #{File.dirname(__FILE__)}/../public/#{file}.html"
          system "rm #{File.dirname(__FILE__)}/../public/#{file}s.html"
          system "rm #{File.dirname(__FILE__)}/../public/#{file}.rss"
          system "rm #{File.dirname(__FILE__)}/../public/#{file}s.rss"
        end
        puts "#{Time.now} - OK!"
    else
        puts "#{Time.now} - ERROR!"
    end
rescue => e
    puts "error!"
    puts e
end